### ISSUE TITLE
Test Backend in Sprint3

### ISSUE THREAD

**Issue by wenzli0510** [ASE-SpaghettiCode/Plan2Go#98]
## Acceptance Criteria:
- [x] Test UserServer, TravelNoteServer and PostServer using unit tests to achieve line coverage of 70% and above.

## Development Tasks:
- [x] #99
- [x] #100
- [x] #101

_Originally posted by @wenzli0510 in https://github.com/ASE-SpaghettiCode/Plan2Go/issues/88#issuecomment-1519033917_

**Comment by duanhuiran** [comment]
This issue was completed a long time ago and should be closed
